name: Coverage Commit Badges (C#)

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build-test-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      # ── Restore & Build pakai solution di src/SampleApp/SampleApp.sln
      - name: Restore
        run: dotnet restore src/SampleApp/SampleApp.sln

      - name: Build (Release)
        run: dotnet build src/SampleApp/SampleApp.sln --no-restore -c Release

      # ── Jalankan test di project test dengan Coverlet
      - name: Test with coverage (NUnit + Coverlet)
        run: |
          dotnet test src/SampleApp/SampleApp.Tests/SampleApp.Tests.csproj --no-build -c Release \
            --logger "trx;LogFileName=TestResults.trx" \
            /p:CollectCoverage=true \
            /p:CoverletOutput=TestResults/Coverage/ \
            /p:CoverletOutputFormat=cobertura \
            /p:Include="[SampleApp*]*" \
            /p:Exclude="[*.Tests*]*" \
            /p:Threshold=80 \
            /p:ThresholdType="line,branch" \
            /p:ThresholdStat=total

      - name: Generate coverage report (ReportGenerator)
        uses: danielpalme/ReportGenerator-GitHub-Action@v5
        with:
          reports: 'src/SampleApp/SampleApp.Tests/TestResults/Coverage/coverage.cobertura.xml'
          targetdir: 'coverage-report'
          reporttypes: 'Badges;MarkdownSummary'
          tag: '${{ github.run_number }}'

      - name: Publish coverage summary to job summary
        if: always()
        run: |
          echo "## Code Coverage Summary" >> $GITHUB_STEP_SUMMARY
          cat coverage-report/Summary.md >> $GITHUB_STEP_SUMMARY || true

      - name: Copy badges into repo
        run: |
          mkdir -p docs/coverage-badges
          cp -f coverage-report/badges/*.svg docs/coverage-badges/

      - name: Commit badges
        run: |
          if [ -n "$(git status --porcelain docs/coverage-badges)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add docs/coverage-badges
            git commit -m "chore: update coverage badges [skip ci]" || true
            git push
          fi
